# Generated by Django 4.0.10 on 2023-08-23 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Siglas', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Vacunas Niños', 'Vacunas Niños'), ('Vacunas', 'Vacunas')], max_length=20, null=True)),
                ('cantidad', models.PositiveIntegerField(null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('principio_activo', models.CharField(max_length=200, null=True)),
                ('proveedor', models.CharField(max_length=200, null=True)),
                ('laboratorio', models.CharField(max_length=200, null=True)),
                ('codigo', models.PositiveIntegerField(null=True)),
                ('unidades_paquete', models.PositiveIntegerField(null=True)),
                ('entrada_unidades', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_address', models.CharField(max_length=40, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('picture', models.ImageField(default='avatar.jpeg', upload_to='Pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
